import { Inter } from 'next/font/google'
import { AuthProvider } from "./providers/session";
import { DataQueryProvider } from "./providers/dataQuery";
import { ErrorBoundary } from "@/app/components/ErrorBoundary";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Home page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ErrorBoundary>
          <DataQueryProvider>
            <AuthProvider>{children}</AuthProvider>
          </DataQueryProvider>
        </ErrorBoundary>
      </body>
    </html>
  )
}
